receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp_grpc/openobserve:
    endpoint: openobserve:5081
    headers:
      Authorization: "Basic YWRtaW5AZXhhbXBsZS5jb206ZlpqM0c2NFVtZ2tCMXZIZQ=="
      organization: default
      stream-name: default
    tls:
      insecure: true

  otlp_http/openobserve:
    endpoint: http://openobserve:5080/api/default
    headers:
      Authorization: "Basic YWRtaW5AZXhhbXBsZS5jb206ZlpqM0c2NFVtZ2tCMXZIZQ=="
      stream-name: default

service:
  telemetry:
    logs:
      level: warn
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp_grpc/openobserve]
    metrics:
      receivers: [otlp]
      exporters: [otlp_grpc/openobserve]
    logs:
      receivers: [otlp]
      exporters: [otlp_http/openobserve]
